version: "1.0"
name: "eurossite-2024"

services:
  db:
    container_name: "local-wordpress-db"
    image: mysql:8.0.29
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    container_name: "admin-tool"
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD: wordpress

  wordpress:
    container_name: "local-wordpress"
    depends_on:
      - db
    image: "wordpress:latest"
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('FS_METHOD', 'direct' );
    volumes:
      - ./themes:/var/www/html/wp-content/themes
      - ./uploads:/var/www/html/wp-content/uploads
      - ./upload.ini:/usr/local/etc/php/conf.d/uploads.ini

volumes:
  db_data:
